name: aliyun_sign
description: A signature helper for Aliyun.
version: 1.0.0
homepage: https://github.com/AlexV525/dart_aliyun_sign

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  crypto: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
